### ISSUE TITLE
superclass mismatch for class Actor

### ISSUE THREAD

**Issue by lucasefe** [mperham/girl_friday#65] opened 2012-11-06 19:12 UTC
Hey, 

I'm getting this error 

```
superclass mismatch for class Actor
```

It happens when I'm trying to use my Actor class (base on AR). It seems like this gem is defining an Actor class on the top level, and that conflicts with the class I have. 

I there a way to help it? The gem provides the GirlFriday namespace, so Actor should probably be defined in that context, IMHO

Thanks

**Comment by jc00ke** [comment] 2012-11-06 19:16
Duplicate of #61 and initially addressed in #60. I'll give it a whirl.

**Closed as completed by jc00ke** 2012-11-06 19:16 UTC
